# Generated by Django 5.2.15 on 2026-07-03 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_partemplate_partemplateitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryunit',
            name='par_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='inventory.partemplate'),
        ),
    ]
