# Generated by Django 5.2.15 on 2026-07-02 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_seed_plans'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invite',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['-created_at']},
        ),
    ]
