# Generated by Django 5.2.15 on 2026-07-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_invite_options_alter_membership_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_subdivisions',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='max_subdivisions_override',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
